### ISSUE TITLE
RequestException Max retires

### ISSUE THREAD

**Issue by d1337ted** [davidhamann/python-fmrest#10]
Hi, First off I really appreciate the work you have done here. It has been a great tool for us. 

I recently started randomly getting an error that I am not sure what to do with. The error started a week ago or so but resolved itself after making no changes to my code the next morning. I'm not even positive that fmrest is the source of the issue so if it is not please let me know. Here is the error I'm seeing when I make my request. 

```
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fmrest/utils.py", line 29, in request
    raise RequestException(ex, args, kwargs) from None
fmrest.exceptions.RequestException: Request error: HTTPSConnectionPool(host='filemaker.example.domain', port=443): Max retries exceeded with url: /fmi/data/v1/databases/example/sessions/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x103b327b8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

```

note: some words were replaced for security. 

please let me know if you have any insight or suggestions. Thanks.

**Comment by davidhamann** [comment]
Hi, thanks for the report.

This exception usually happens when the server cannot be reached / the DNS name cannot be resolved.

Maybe you can find out more by looking at other log files for the same time (maybe the host was down, your DNS server was down, ...). Unfortunately, this is nothing I could debug from here.

If you have other questions related to this, feel free to comment again. Will close the ticket for now.
